title: "TI no Canadá"
description: "Um grupo no telegram sobre tecnologia e imigração para o Canadá"
baseurl: "/imigracao-para-o-canada/"
url: "https://ti-no-canada.github.io/imigracao-para-o-canada"

theme: minima

sass:
  style: compressed
  load_paths:
    - assets/_sass

header_pages:
  - README.md

social_links:
  telegram: "https://t.me/tinocanada"
  github: "https://github.com/ti-no-canada"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM

include:
  - assets
